/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ReportId = IDL.Nat;
export const AddCommentRequest = IDL.Record({
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'dansalId' : IDL.Nat,
});
export const CommentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'dansalId' : IDL.Nat,
  'timestamp' : Timestamp,
  'authorPrincipal' : IDL.Principal,
});
export const AddDansalRequest = IDL.Record({
  'latitude' : IDL.Float64,
  'contactName' : IDL.Text,
  'province' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'organizerName' : IDL.Text,
  'district' : IDL.Text,
  'foodTypes' : IDL.Vec(IDL.Text),
  'longitude' : IDL.Float64,
  'category' : IDL.Text,
  'locationLink' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const DansalId = IDL.Nat;
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Dansal = IDL.Record({
  'id' : DansalId,
  'status' : ApprovalStatus,
  'latitude' : IDL.Float64,
  'contactName' : IDL.Text,
  'province' : IDL.Text,
  'appreciationCount' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'organizerName' : IDL.Text,
  'likedBy' : IDL.Vec(IDL.Principal),
  'district' : IDL.Text,
  'foodTypes' : IDL.Vec(IDL.Text),
  'viewCount' : IDL.Nat,
  'longitude' : IDL.Float64,
  'organizerPrincipal' : IDL.Principal,
  'category' : IDL.Text,
  'locationLink' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AddPhotoRequest = IDL.Record({
  'uploaderName' : IDL.Text,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const PhotoId = IDL.Nat;
export const GalleryPhoto = IDL.Record({
  'id' : PhotoId,
  'status' : ApprovalStatus,
  'uploaderName' : IDL.Text,
  'appreciationCount' : IDL.Nat,
  'likedBy' : IDL.Vec(IDL.Principal),
  'uploaderPrincipal' : IDL.Principal,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});
export const AddPhotoCommentRequest = IDL.Record({
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'photoId' : IDL.Nat,
});
export const PhotoCommentId = IDL.Nat;
export const PhotoComment = IDL.Record({
  'id' : PhotoCommentId,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : Timestamp,
  'authorPrincipal' : IDL.Principal,
  'photoId' : IDL.Nat,
});
export const AddReportNoteRequest = IDL.Record({
  'text' : IDL.Text,
  'reportId' : ReportId,
});
export const NoteId = IDL.Nat;
export const AddReviewRequest = IDL.Record({
  'text' : IDL.Text,
  'reviewerName' : IDL.Text,
  'dansalId' : IDL.Nat,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'text' : IDL.Text,
  'reviewerName' : IDL.Text,
  'dansalId' : IDL.Nat,
  'timestamp' : Timestamp,
  'reviewerPrincipal' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const DansalFilter = IDL.Record({
  'province' : IDL.Opt(IDL.Text),
  'timeStart' : IDL.Opt(IDL.Text),
  'district' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'timeEnd' : IDL.Opt(IDL.Text),
  'foodType' : IDL.Opt(IDL.Text),
});
export const ReportTargetType = IDL.Variant({
  'dansal' : IDL.Null,
  'photo' : IDL.Null,
});
export const ApprovalNotification = IDL.Record({
  'id' : IDL.Nat,
  'approvedAt' : IDL.Int,
  'seen' : IDL.Bool,
  'targetName' : IDL.Text,
  'targetType' : ReportTargetType,
  'targetId' : IDL.Nat,
});
export const DansalAnalytics = IDL.Record({
  'likeCount' : IDL.Nat,
  'appreciationCount' : IDL.Nat,
  'name' : IDL.Text,
  'viewCount' : IDL.Nat,
  'dansalId' : IDL.Nat,
});
export const Role = IDL.Variant({
  'organizer' : IDL.Null,
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'superAdmin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'role' : Role,
  'bioUpdatedAt' : IDL.Opt(IDL.Int),
  'registeredAt' : IDL.Int,
});
export const OrganizerPublicProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'totalViews' : IDL.Nat,
  'name' : IDL.Text,
  'totalDansals' : IDL.Nat,
  'totalLikes' : IDL.Nat,
  'avgRating' : IDL.Float64,
});
export const ReportNote = IDL.Record({
  'id' : NoteId,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'reportId' : ReportId,
});
export const ReportStatus = IDL.Variant({
  'pending' : IDL.Null,
  'dismissed' : IDL.Null,
  'actioned' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : ReportId,
  'status' : ReportStatus,
  'description' : IDL.Opt(IDL.Text),
  'reporterPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'targetType' : ReportTargetType,
  'targetId' : IDL.Nat,
  'reason' : IDL.Variant({
    'other' : IDL.Null,
    'fake' : IDL.Null,
    'inappropriate' : IDL.Null,
    'spam' : IDL.Null,
  }),
});
export const SubmitReportRequest = IDL.Record({
  'description' : IDL.Opt(IDL.Text),
  'targetType' : ReportTargetType,
  'targetId' : IDL.Nat,
  'reason' : IDL.Variant({
    'other' : IDL.Null,
    'fake' : IDL.Null,
    'inappropriate' : IDL.Null,
    'spam' : IDL.Null,
  }),
});
export const LikeResult = IDL.Record({
  'likeCount' : IDL.Nat,
  'liked' : IDL.Bool,
});
export const UpdateDansalRequest = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'contactName' : IDL.Opt(IDL.Text),
  'province' : IDL.Opt(IDL.Text),
  'date' : IDL.Opt(IDL.Text),
  'time' : IDL.Opt(IDL.Text),
  'organizerName' : IDL.Opt(IDL.Text),
  'district' : IDL.Opt(IDL.Text),
  'foodTypes' : IDL.Opt(IDL.Vec(IDL.Text)),
  'longitude' : IDL.Opt(IDL.Float64),
  'category' : IDL.Opt(IDL.Text),
  'locationLink' : IDL.Opt(IDL.Text),
  'contactPhone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'actionReport' : IDL.Func(
      [ReportId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addComment' : IDL.Func([AddCommentRequest], [Comment], []),
  'addDansal' : IDL.Func([AddDansalRequest], [Dansal], []),
  'addGalleryPhoto' : IDL.Func([AddPhotoRequest], [GalleryPhoto], []),
  'addPhotoComment' : IDL.Func(
      [AddPhotoCommentRequest],
      [IDL.Variant({ 'ok' : PhotoComment, 'err' : IDL.Text })],
      [],
    ),
  'addReportNote' : IDL.Func(
      [AddReportNoteRequest],
      [IDL.Variant({ 'ok' : NoteId, 'err' : IDL.Text })],
      [],
    ),
  'addReview' : IDL.Func(
      [AddReviewRequest],
      [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
      [],
    ),
  'appreciateDansal' : IDL.Func([DansalId], [IDL.Bool], []),
  'appreciatePhoto' : IDL.Func([PhotoId], [IDL.Bool], []),
  'approveDansal' : IDL.Func(
      [DansalId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approvePhoto' : IDL.Func(
      [PhotoId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'changeAdminPin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteComment' : IDL.Func(
      [CommentId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteDansal' : IDL.Func(
      [DansalId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deletePhotoComment' : IDL.Func(
      [PhotoCommentId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteReportNote' : IDL.Func(
      [NoteId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteReview' : IDL.Func(
      [ReviewId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'dismissReport' : IDL.Func(
      [ReportId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'filterDansals' : IDL.Func([DansalFilter], [IDL.Vec(Dansal)], ['query']),
  'getApprovalNotifications' : IDL.Func(
      [],
      [IDL.Vec(ApprovalNotification)],
      ['query'],
    ),
  'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getDansal' : IDL.Func([DansalId], [IDL.Opt(Dansal)], []),
  'getDansals' : IDL.Func([], [IDL.Vec(Dansal)], ['query']),
  'getGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
  'getMyDansalAnalytics' : IDL.Func([], [IDL.Vec(DansalAnalytics)], ['query']),
  'getMyDansals' : IDL.Func([], [IDL.Vec(Dansal)], ['query']),
  'getMyFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getOrganizerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(OrganizerPublicProfile)],
      ['query'],
    ),
  'getPendingDansals' : IDL.Func([], [IDL.Vec(Dansal)], []),
  'getPendingPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], []),
  'getPhotoComments' : IDL.Func([IDL.Nat], [IDL.Vec(PhotoComment)], ['query']),
  'getReportNotes' : IDL.Func([ReportId], [IDL.Vec(ReportNote)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'isDansalLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isFavorited' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'likePhoto' : IDL.Func([PhotoId], [IDL.Bool], []),
  'listDansals' : IDL.Func([], [IDL.Vec(Dansal)], ['query']),
  'listPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], []),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
  'markNotificationSeen' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text], [UserProfile], []),
  'rejectDansal' : IDL.Func(
      [DansalId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'rejectPhoto' : IDL.Func(
      [PhotoId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setUserRole' : IDL.Func(
      [IDL.Principal, Role],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitReport' : IDL.Func([SubmitReportRequest], [Report], []),
  'toggleDansalLike' : IDL.Func([IDL.Nat], [LikeResult], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'togglePhotoLike' : IDL.Func([IDL.Nat], [LikeResult], []),
  'updateDansal' : IDL.Func(
      [DansalId, UpdateDansalRequest],
      [IDL.Variant({ 'ok' : Dansal, 'err' : IDL.Text })],
      [],
    ),
  'updateOrganizerBio' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadPhoto' : IDL.Func([AddPhotoRequest], [GalleryPhoto], []),
  'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ReportId = IDL.Nat;
  const AddCommentRequest = IDL.Record({
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'dansalId' : IDL.Nat,
  });
  const CommentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'dansalId' : IDL.Nat,
    'timestamp' : Timestamp,
    'authorPrincipal' : IDL.Principal,
  });
  const AddDansalRequest = IDL.Record({
    'latitude' : IDL.Float64,
    'contactName' : IDL.Text,
    'province' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'organizerName' : IDL.Text,
    'district' : IDL.Text,
    'foodTypes' : IDL.Vec(IDL.Text),
    'longitude' : IDL.Float64,
    'category' : IDL.Text,
    'locationLink' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const DansalId = IDL.Nat;
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Dansal = IDL.Record({
    'id' : DansalId,
    'status' : ApprovalStatus,
    'latitude' : IDL.Float64,
    'contactName' : IDL.Text,
    'province' : IDL.Text,
    'appreciationCount' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'organizerName' : IDL.Text,
    'likedBy' : IDL.Vec(IDL.Principal),
    'district' : IDL.Text,
    'foodTypes' : IDL.Vec(IDL.Text),
    'viewCount' : IDL.Nat,
    'longitude' : IDL.Float64,
    'organizerPrincipal' : IDL.Principal,
    'category' : IDL.Text,
    'locationLink' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AddPhotoRequest = IDL.Record({
    'uploaderName' : IDL.Text,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const PhotoId = IDL.Nat;
  const GalleryPhoto = IDL.Record({
    'id' : PhotoId,
    'status' : ApprovalStatus,
    'uploaderName' : IDL.Text,
    'appreciationCount' : IDL.Nat,
    'likedBy' : IDL.Vec(IDL.Principal),
    'uploaderPrincipal' : IDL.Principal,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  const AddPhotoCommentRequest = IDL.Record({
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'photoId' : IDL.Nat,
  });
  const PhotoCommentId = IDL.Nat;
  const PhotoComment = IDL.Record({
    'id' : PhotoCommentId,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : Timestamp,
    'authorPrincipal' : IDL.Principal,
    'photoId' : IDL.Nat,
  });
  const AddReportNoteRequest = IDL.Record({
    'text' : IDL.Text,
    'reportId' : ReportId,
  });
  const NoteId = IDL.Nat;
  const AddReviewRequest = IDL.Record({
    'text' : IDL.Text,
    'reviewerName' : IDL.Text,
    'dansalId' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'text' : IDL.Text,
    'reviewerName' : IDL.Text,
    'dansalId' : IDL.Nat,
    'timestamp' : Timestamp,
    'reviewerPrincipal' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const DansalFilter = IDL.Record({
    'province' : IDL.Opt(IDL.Text),
    'timeStart' : IDL.Opt(IDL.Text),
    'district' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'timeEnd' : IDL.Opt(IDL.Text),
    'foodType' : IDL.Opt(IDL.Text),
  });
  const ReportTargetType = IDL.Variant({
    'dansal' : IDL.Null,
    'photo' : IDL.Null,
  });
  const ApprovalNotification = IDL.Record({
    'id' : IDL.Nat,
    'approvedAt' : IDL.Int,
    'seen' : IDL.Bool,
    'targetName' : IDL.Text,
    'targetType' : ReportTargetType,
    'targetId' : IDL.Nat,
  });
  const DansalAnalytics = IDL.Record({
    'likeCount' : IDL.Nat,
    'appreciationCount' : IDL.Nat,
    'name' : IDL.Text,
    'viewCount' : IDL.Nat,
    'dansalId' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'organizer' : IDL.Null,
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'superAdmin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'role' : Role,
    'bioUpdatedAt' : IDL.Opt(IDL.Int),
    'registeredAt' : IDL.Int,
  });
  const OrganizerPublicProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'totalViews' : IDL.Nat,
    'name' : IDL.Text,
    'totalDansals' : IDL.Nat,
    'totalLikes' : IDL.Nat,
    'avgRating' : IDL.Float64,
  });
  const ReportNote = IDL.Record({
    'id' : NoteId,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'reportId' : ReportId,
  });
  const ReportStatus = IDL.Variant({
    'pending' : IDL.Null,
    'dismissed' : IDL.Null,
    'actioned' : IDL.Null,
  });
  const Report = IDL.Record({
    'id' : ReportId,
    'status' : ReportStatus,
    'description' : IDL.Opt(IDL.Text),
    'reporterPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'targetType' : ReportTargetType,
    'targetId' : IDL.Nat,
    'reason' : IDL.Variant({
      'other' : IDL.Null,
      'fake' : IDL.Null,
      'inappropriate' : IDL.Null,
      'spam' : IDL.Null,
    }),
  });
  const SubmitReportRequest = IDL.Record({
    'description' : IDL.Opt(IDL.Text),
    'targetType' : ReportTargetType,
    'targetId' : IDL.Nat,
    'reason' : IDL.Variant({
      'other' : IDL.Null,
      'fake' : IDL.Null,
      'inappropriate' : IDL.Null,
      'spam' : IDL.Null,
    }),
  });
  const LikeResult = IDL.Record({ 'likeCount' : IDL.Nat, 'liked' : IDL.Bool });
  const UpdateDansalRequest = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'contactName' : IDL.Opt(IDL.Text),
    'province' : IDL.Opt(IDL.Text),
    'date' : IDL.Opt(IDL.Text),
    'time' : IDL.Opt(IDL.Text),
    'organizerName' : IDL.Opt(IDL.Text),
    'district' : IDL.Opt(IDL.Text),
    'foodTypes' : IDL.Opt(IDL.Vec(IDL.Text)),
    'longitude' : IDL.Opt(IDL.Float64),
    'category' : IDL.Opt(IDL.Text),
    'locationLink' : IDL.Opt(IDL.Text),
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'actionReport' : IDL.Func(
        [ReportId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addComment' : IDL.Func([AddCommentRequest], [Comment], []),
    'addDansal' : IDL.Func([AddDansalRequest], [Dansal], []),
    'addGalleryPhoto' : IDL.Func([AddPhotoRequest], [GalleryPhoto], []),
    'addPhotoComment' : IDL.Func(
        [AddPhotoCommentRequest],
        [IDL.Variant({ 'ok' : PhotoComment, 'err' : IDL.Text })],
        [],
      ),
    'addReportNote' : IDL.Func(
        [AddReportNoteRequest],
        [IDL.Variant({ 'ok' : NoteId, 'err' : IDL.Text })],
        [],
      ),
    'addReview' : IDL.Func(
        [AddReviewRequest],
        [IDL.Variant({ 'ok' : Review, 'err' : IDL.Text })],
        [],
      ),
    'appreciateDansal' : IDL.Func([DansalId], [IDL.Bool], []),
    'appreciatePhoto' : IDL.Func([PhotoId], [IDL.Bool], []),
    'approveDansal' : IDL.Func(
        [DansalId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approvePhoto' : IDL.Func(
        [PhotoId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'changeAdminPin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteComment' : IDL.Func(
        [CommentId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteDansal' : IDL.Func(
        [DansalId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deletePhotoComment' : IDL.Func(
        [PhotoCommentId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteReportNote' : IDL.Func(
        [NoteId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteReview' : IDL.Func(
        [ReviewId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'dismissReport' : IDL.Func(
        [ReportId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'filterDansals' : IDL.Func([DansalFilter], [IDL.Vec(Dansal)], ['query']),
    'getApprovalNotifications' : IDL.Func(
        [],
        [IDL.Vec(ApprovalNotification)],
        ['query'],
      ),
    'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getDansal' : IDL.Func([DansalId], [IDL.Opt(Dansal)], []),
    'getDansals' : IDL.Func([], [IDL.Vec(Dansal)], ['query']),
    'getGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
    'getMyDansalAnalytics' : IDL.Func(
        [],
        [IDL.Vec(DansalAnalytics)],
        ['query'],
      ),
    'getMyDansals' : IDL.Func([], [IDL.Vec(Dansal)], ['query']),
    'getMyFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getOrganizerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(OrganizerPublicProfile)],
        ['query'],
      ),
    'getPendingDansals' : IDL.Func([], [IDL.Vec(Dansal)], []),
    'getPendingPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], []),
    'getPhotoComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PhotoComment)],
        ['query'],
      ),
    'getReportNotes' : IDL.Func([ReportId], [IDL.Vec(ReportNote)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'isDansalLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isFavorited' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'likePhoto' : IDL.Func([PhotoId], [IDL.Bool], []),
    'listDansals' : IDL.Func([], [IDL.Vec(Dansal)], ['query']),
    'listPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], []),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
    'markNotificationSeen' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text], [UserProfile], []),
    'rejectDansal' : IDL.Func(
        [DansalId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'rejectPhoto' : IDL.Func(
        [PhotoId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setUserRole' : IDL.Func(
        [IDL.Principal, Role],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitReport' : IDL.Func([SubmitReportRequest], [Report], []),
    'toggleDansalLike' : IDL.Func([IDL.Nat], [LikeResult], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'togglePhotoLike' : IDL.Func([IDL.Nat], [LikeResult], []),
    'updateDansal' : IDL.Func(
        [DansalId, UpdateDansalRequest],
        [IDL.Variant({ 'ok' : Dansal, 'err' : IDL.Text })],
        [],
      ),
    'updateOrganizerBio' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadPhoto' : IDL.Func([AddPhotoRequest], [GalleryPhoto], []),
    'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };