/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddCommentRequest {
  'text' : string,
  'authorName' : string,
  'dansalId' : bigint,
}
export interface AddDansalRequest {
  'latitude' : number,
  'contactName' : string,
  'province' : string,
  'date' : string,
  'time' : string,
  'organizerName' : string,
  'district' : string,
  'foodTypes' : Array<string>,
  'longitude' : number,
  'category' : string,
  'locationLink' : string,
  'contactPhone' : string,
}
export interface AddPhotoCommentRequest {
  'text' : string,
  'authorName' : string,
  'photoId' : bigint,
}
export interface AddPhotoRequest {
  'uploaderName' : string,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface AddReportNoteRequest { 'text' : string, 'reportId' : ReportId }
export interface AddReviewRequest {
  'text' : string,
  'reviewerName' : string,
  'dansalId' : bigint,
  'rating' : bigint,
}
export interface ApprovalNotification {
  'id' : bigint,
  'approvedAt' : bigint,
  'seen' : boolean,
  'targetName' : string,
  'targetType' : ReportTargetType,
  'targetId' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Comment {
  'id' : CommentId,
  'text' : string,
  'authorName' : string,
  'dansalId' : bigint,
  'timestamp' : Timestamp,
  'authorPrincipal' : Principal,
}
export type CommentId = bigint;
export interface Dansal {
  'id' : DansalId,
  'status' : ApprovalStatus,
  'latitude' : number,
  'contactName' : string,
  'province' : string,
  'appreciationCount' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'time' : string,
  'organizerName' : string,
  'likedBy' : Array<Principal>,
  'district' : string,
  'foodTypes' : Array<string>,
  'viewCount' : bigint,
  'longitude' : number,
  'organizerPrincipal' : Principal,
  'category' : string,
  'locationLink' : string,
  'contactPhone' : string,
}
export interface DansalAnalytics {
  'likeCount' : bigint,
  'appreciationCount' : bigint,
  'name' : string,
  'viewCount' : bigint,
  'dansalId' : bigint,
}
export interface DansalFilter {
  'province' : [] | [string],
  'timeStart' : [] | [string],
  'district' : [] | [string],
  'category' : [] | [string],
  'timeEnd' : [] | [string],
  'foodType' : [] | [string],
}
export type DansalId = bigint;
export type ExternalBlob = Uint8Array;
export interface GalleryPhoto {
  'id' : PhotoId,
  'status' : ApprovalStatus,
  'uploaderName' : string,
  'appreciationCount' : bigint,
  'likedBy' : Array<Principal>,
  'uploaderPrincipal' : Principal,
  'caption' : string,
  'image' : ExternalBlob,
  'uploadedAt' : bigint,
}
export interface LikeResult { 'likeCount' : bigint, 'liked' : boolean }
export type NoteId = bigint;
export interface OrganizerPublicProfile {
  'bio' : string,
  'principal' : Principal,
  'totalViews' : bigint,
  'name' : string,
  'totalDansals' : bigint,
  'totalLikes' : bigint,
  'avgRating' : number,
}
export interface PhotoComment {
  'id' : PhotoCommentId,
  'text' : string,
  'authorName' : string,
  'timestamp' : Timestamp,
  'authorPrincipal' : Principal,
  'photoId' : bigint,
}
export type PhotoCommentId = bigint;
export type PhotoId = bigint;
export interface Report {
  'id' : ReportId,
  'status' : ReportStatus,
  'description' : [] | [string],
  'reporterPrincipal' : Principal,
  'timestamp' : bigint,
  'targetType' : ReportTargetType,
  'targetId' : bigint,
  'reason' : { 'other' : null } |
    { 'fake' : null } |
    { 'inappropriate' : null } |
    { 'spam' : null },
}
export type ReportId = bigint;
export interface ReportNote {
  'id' : NoteId,
  'authorId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'authorName' : string,
  'reportId' : ReportId,
}
export type ReportStatus = { 'pending' : null } |
  { 'dismissed' : null } |
  { 'actioned' : null };
export type ReportTargetType = { 'dansal' : null } |
  { 'photo' : null };
export interface Review {
  'id' : ReviewId,
  'text' : string,
  'reviewerName' : string,
  'dansalId' : bigint,
  'timestamp' : Timestamp,
  'reviewerPrincipal' : Principal,
  'rating' : bigint,
}
export type ReviewId = bigint;
export type Role = { 'organizer' : null } |
  { 'admin' : null } |
  { 'user' : null } |
  { 'superAdmin' : null };
export interface SubmitReportRequest {
  'description' : [] | [string],
  'targetType' : ReportTargetType,
  'targetId' : bigint,
  'reason' : { 'other' : null } |
    { 'fake' : null } |
    { 'inappropriate' : null } |
    { 'spam' : null },
}
export type Timestamp = bigint;
export interface UpdateDansalRequest {
  'latitude' : [] | [number],
  'contactName' : [] | [string],
  'province' : [] | [string],
  'date' : [] | [string],
  'time' : [] | [string],
  'organizerName' : [] | [string],
  'district' : [] | [string],
  'foodTypes' : [] | [Array<string>],
  'longitude' : [] | [number],
  'category' : [] | [string],
  'locationLink' : [] | [string],
  'contactPhone' : [] | [string],
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'displayName' : string,
  'role' : Role,
  'bioUpdatedAt' : [] | [bigint],
  'registeredAt' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'actionReport' : ActorMethod<
    [ReportId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addComment' : ActorMethod<[AddCommentRequest], Comment>,
  'addDansal' : ActorMethod<[AddDansalRequest], Dansal>,
  'addGalleryPhoto' : ActorMethod<[AddPhotoRequest], GalleryPhoto>,
  'addPhotoComment' : ActorMethod<
    [AddPhotoCommentRequest],
    { 'ok' : PhotoComment } |
      { 'err' : string }
  >,
  'addReportNote' : ActorMethod<
    [AddReportNoteRequest],
    { 'ok' : NoteId } |
      { 'err' : string }
  >,
  'addReview' : ActorMethod<
    [AddReviewRequest],
    { 'ok' : Review } |
      { 'err' : string }
  >,
  'appreciateDansal' : ActorMethod<[DansalId], boolean>,
  'appreciatePhoto' : ActorMethod<[PhotoId], boolean>,
  'approveDansal' : ActorMethod<
    [DansalId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approvePhoto' : ActorMethod<[PhotoId], { 'ok' : null } | { 'err' : string }>,
  'changeAdminPin' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteComment' : ActorMethod<
    [CommentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteDansal' : ActorMethod<
    [DansalId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deletePhotoComment' : ActorMethod<
    [PhotoCommentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteReportNote' : ActorMethod<
    [NoteId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteReview' : ActorMethod<
    [ReviewId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteUser' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'dismissReport' : ActorMethod<
    [ReportId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'filterDansals' : ActorMethod<[DansalFilter], Array<Dansal>>,
  'getApprovalNotifications' : ActorMethod<[], Array<ApprovalNotification>>,
  'getAverageRating' : ActorMethod<[bigint], number>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getDansal' : ActorMethod<[DansalId], [] | [Dansal]>,
  'getDansals' : ActorMethod<[], Array<Dansal>>,
  'getGalleryPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'getMyDansalAnalytics' : ActorMethod<[], Array<DansalAnalytics>>,
  'getMyDansals' : ActorMethod<[], Array<Dansal>>,
  'getMyFavorites' : ActorMethod<[], Array<bigint>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getOrganizerProfile' : ActorMethod<
    [Principal],
    [] | [OrganizerPublicProfile]
  >,
  'getPendingDansals' : ActorMethod<[], Array<Dansal>>,
  'getPendingPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'getPhotoComments' : ActorMethod<[bigint], Array<PhotoComment>>,
  'getReportNotes' : ActorMethod<[ReportId], Array<ReportNote>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'isDansalLiked' : ActorMethod<[bigint], boolean>,
  'isFavorited' : ActorMethod<[bigint], boolean>,
  'likePhoto' : ActorMethod<[PhotoId], boolean>,
  'listDansals' : ActorMethod<[], Array<Dansal>>,
  'listPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'listReports' : ActorMethod<[], Array<Report>>,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'markNotificationSeen' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string], UserProfile>,
  'rejectDansal' : ActorMethod<
    [DansalId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'rejectPhoto' : ActorMethod<[PhotoId], { 'ok' : null } | { 'err' : string }>,
  'setUserRole' : ActorMethod<
    [Principal, Role],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitReport' : ActorMethod<[SubmitReportRequest], Report>,
  'toggleDansalLike' : ActorMethod<[bigint], LikeResult>,
  'toggleFavorite' : ActorMethod<[bigint], boolean>,
  'togglePhotoLike' : ActorMethod<[bigint], LikeResult>,
  'updateDansal' : ActorMethod<
    [DansalId, UpdateDansalRequest],
    { 'ok' : Dansal } |
      { 'err' : string }
  >,
  'updateOrganizerBio' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadPhoto' : ActorMethod<[AddPhotoRequest], GalleryPhoto>,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];