/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type PhotoId = bigint;
export interface Dansal {
    id: DansalId;
    status: ApprovalStatus;
    latitude: number;
    contactName: string;
    province: string;
    appreciationCount: bigint;
    date: string;
    createdAt: bigint;
    time: string;
    organizerName: string;
    likedBy: Array<Principal>;
    district: string;
    foodTypes: Array<string>;
    viewCount: bigint;
    longitude: number;
    organizerPrincipal: Principal;
    category: string;
    locationLink: string;
    contactPhone: string;
}
export interface Report {
    id: ReportId;
    status: ReportStatus;
    description?: string;
    reporterPrincipal: Principal;
    timestamp: bigint;
    targetType: ReportTargetType;
    targetId: bigint;
    reason: Variant_other_fake_inappropriate_spam;
}
export interface AddReviewRequest {
    text: string;
    reviewerName: string;
    dansalId: bigint;
    rating: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type ReportId = bigint;
export interface DansalFilter {
    province?: string;
    timeStart?: string;
    district?: string;
    category?: string;
    timeEnd?: string;
    foodType?: string;
}
export interface DansalAnalytics {
    likeCount: bigint;
    appreciationCount: bigint;
    name: string;
    viewCount: bigint;
    dansalId: bigint;
}
export interface PhotoComment {
    id: PhotoCommentId;
    text: string;
    authorName: string;
    timestamp: Timestamp;
    authorPrincipal: Principal;
    photoId: bigint;
}
export interface UpdateDansalRequest {
    latitude?: number;
    contactName?: string;
    province?: string;
    date?: string;
    time?: string;
    organizerName?: string;
    district?: string;
    foodTypes?: Array<string>;
    longitude?: number;
    category?: string;
    locationLink?: string;
    contactPhone?: string;
}
export interface AddCommentRequest {
    text: string;
    authorName: string;
    dansalId: bigint;
}
export type ReviewId = bigint;
export interface AddDansalRequest {
    latitude: number;
    contactName: string;
    province: string;
    date: string;
    time: string;
    organizerName: string;
    district: string;
    foodTypes: Array<string>;
    longitude: number;
    category: string;
    locationLink: string;
    contactPhone: string;
}
export interface LikeResult {
    likeCount: bigint;
    liked: boolean;
}
export interface Review {
    id: ReviewId;
    text: string;
    reviewerName: string;
    dansalId: bigint;
    timestamp: Timestamp;
    reviewerPrincipal: Principal;
    rating: bigint;
}
export interface ApprovalNotification {
    id: bigint;
    approvedAt: bigint;
    seen: boolean;
    targetName: string;
    targetType: ReportTargetType;
    targetId: bigint;
}
export type NoteId = bigint;
export interface GalleryPhoto {
    id: PhotoId;
    status: ApprovalStatus;
    uploaderName: string;
    appreciationCount: bigint;
    likedBy: Array<Principal>;
    uploaderPrincipal: Principal;
    caption: string;
    image: ExternalBlob;
    uploadedAt: bigint;
}
export interface SubmitReportRequest {
    description?: string;
    targetType: ReportTargetType;
    targetId: bigint;
    reason: Variant_other_fake_inappropriate_spam;
}
export interface ReportNote {
    id: NoteId;
    authorId: Principal;
    createdAt: bigint;
    text: string;
    authorName: string;
    reportId: ReportId;
}
export type CommentId = bigint;
export type PhotoCommentId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Comment {
    id: CommentId;
    text: string;
    authorName: string;
    dansalId: bigint;
    timestamp: Timestamp;
    authorPrincipal: Principal;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AddPhotoCommentRequest {
    text: string;
    authorName: string;
    photoId: bigint;
}
export interface AddPhotoRequest {
    uploaderName: string;
    caption: string;
    image: ExternalBlob;
}
export interface OrganizerPublicProfile {
    bio: string;
    principal: Principal;
    totalViews: bigint;
    name: string;
    totalDansals: bigint;
    totalLikes: bigint;
    avgRating: number;
}
export type DansalId = bigint;
export interface AddReportNoteRequest {
    text: string;
    reportId: ReportId;
}
export interface UserProfile {
    bio: string;
    principal: Principal;
    displayName: string;
    role: Role;
    bioUpdatedAt?: bigint;
    registeredAt: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ReportStatus {
    pending = "pending",
    dismissed = "dismissed",
    actioned = "actioned"
}
export enum ReportTargetType {
    dansal = "dansal",
    photo = "photo"
}
export enum Role {
    organizer = "organizer",
    admin = "admin",
    user = "user",
    superAdmin = "superAdmin"
}
export enum Variant_other_fake_inappropriate_spam {
    other = "other",
    fake = "fake",
    inappropriate = "inappropriate",
    spam = "spam"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    actionReport(id: ReportId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addComment(req: AddCommentRequest): Promise<Comment>;
    addDansal(req: AddDansalRequest): Promise<Dansal>;
    addGalleryPhoto(req: AddPhotoRequest): Promise<GalleryPhoto>;
    addPhotoComment(req: AddPhotoCommentRequest): Promise<{
        __kind__: "ok";
        ok: PhotoComment;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addReportNote(req: AddReportNoteRequest): Promise<{
        __kind__: "ok";
        ok: NoteId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addReview(req: AddReviewRequest): Promise<{
        __kind__: "ok";
        ok: Review;
    } | {
        __kind__: "err";
        err: string;
    }>;
    appreciateDansal(id: DansalId): Promise<boolean>;
    appreciatePhoto(id: PhotoId): Promise<boolean>;
    approveDansal(id: DansalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    approvePhoto(id: PhotoId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    changeAdminPin(oldPin: string, newPin: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteComment(id: CommentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteDansal(id: DansalId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deletePhotoComment(id: PhotoCommentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteReportNote(noteId: NoteId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteReview(id: ReviewId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteUser(target: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    dismissReport(id: ReportId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    filterDansals(filter: DansalFilter): Promise<Array<Dansal>>;
    getApprovalNotifications(): Promise<Array<ApprovalNotification>>;
    getAverageRating(dansalId: bigint): Promise<number>;
    getComments(dansalId: bigint): Promise<Array<Comment>>;
    getDansal(id: DansalId): Promise<Dansal | null>;
    getDansals(): Promise<Array<Dansal>>;
    getGalleryPhotos(): Promise<Array<GalleryPhoto>>;
    getMyDansalAnalytics(): Promise<Array<DansalAnalytics>>;
    getMyDansals(): Promise<Array<Dansal>>;
    getMyFavorites(): Promise<Array<bigint>>;
    getMyProfile(): Promise<UserProfile | null>;
    getOrganizerProfile(principal: Principal): Promise<OrganizerPublicProfile | null>;
    getPendingDansals(): Promise<Array<Dansal>>;
    getPendingPhotos(): Promise<Array<GalleryPhoto>>;
    getPhotoComments(photoId: bigint): Promise<Array<PhotoComment>>;
    getReportNotes(reportId: ReportId): Promise<Array<ReportNote>>;
    getReviews(dansalId: bigint): Promise<Array<Review>>;
    isDansalLiked(dansalId: bigint): Promise<boolean>;
    isFavorited(dansalId: bigint): Promise<boolean>;
    likePhoto(id: PhotoId): Promise<boolean>;
    listDansals(): Promise<Array<Dansal>>;
    listPhotos(): Promise<Array<GalleryPhoto>>;
    listReports(): Promise<Array<Report>>;
    listUsers(): Promise<Array<UserProfile>>;
    markNotificationSeen(id: bigint): Promise<void>;
    registerUser(displayName: string): Promise<UserProfile>;
    rejectDansal(id: DansalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    rejectPhoto(id: PhotoId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setUserRole(target: Principal, role: Role): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitReport(req: SubmitReportRequest): Promise<Report>;
    toggleDansalLike(dansalId: bigint): Promise<LikeResult>;
    toggleFavorite(dansalId: bigint): Promise<boolean>;
    togglePhotoLike(photoId: bigint): Promise<LikeResult>;
    updateDansal(id: DansalId, req: UpdateDansalRequest): Promise<{
        __kind__: "ok";
        ok: Dansal;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateOrganizerBio(bio: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    uploadPhoto(req: AddPhotoRequest): Promise<GalleryPhoto>;
    verifyAdminPin(pin: string): Promise<boolean>;
}
import type { AddPhotoRequest as _AddPhotoRequest, ApprovalNotification as _ApprovalNotification, ApprovalStatus as _ApprovalStatus, Dansal as _Dansal, DansalFilter as _DansalFilter, DansalId as _DansalId, ExternalBlob as _ExternalBlob, GalleryPhoto as _GalleryPhoto, NoteId as _NoteId, OrganizerPublicProfile as _OrganizerPublicProfile, PhotoComment as _PhotoComment, PhotoId as _PhotoId, Report as _Report, ReportId as _ReportId, ReportStatus as _ReportStatus, ReportTargetType as _ReportTargetType, Review as _Review, Role as _Role, SubmitReportRequest as _SubmitReportRequest, UpdateDansalRequest as _UpdateDansalRequest, UserProfile as _UserProfile, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async actionReport(arg0: ReportId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.actionReport(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.actionReport(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addComment(arg0: AddCommentRequest): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0);
            return result;
        }
    }
    async addDansal(arg0: AddDansalRequest): Promise<Dansal> {
        if (this.processError) {
            try {
                const result = await this.actor.addDansal(arg0);
                return from_candid_Dansal_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDansal(arg0);
            return from_candid_Dansal_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addGalleryPhoto(arg0: AddPhotoRequest): Promise<GalleryPhoto> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryPhoto(await to_candid_AddPhotoRequest_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GalleryPhoto_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryPhoto(await to_candid_AddPhotoRequest_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GalleryPhoto_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPhotoComment(arg0: AddPhotoCommentRequest): Promise<{
        __kind__: "ok";
        ok: PhotoComment;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhotoComment(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhotoComment(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReportNote(arg0: AddReportNoteRequest): Promise<{
        __kind__: "ok";
        ok: NoteId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReportNote(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReportNote(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReview(arg0: AddReviewRequest): Promise<{
        __kind__: "ok";
        ok: Review;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async appreciateDansal(arg0: DansalId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.appreciateDansal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appreciateDansal(arg0);
            return result;
        }
    }
    async appreciatePhoto(arg0: PhotoId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.appreciatePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appreciatePhoto(arg0);
            return result;
        }
    }
    async approveDansal(arg0: DansalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDansal(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDansal(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async approvePhoto(arg0: PhotoId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePhoto(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePhoto(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async changeAdminPin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPin(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPin(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: CommentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDansal(arg0: DansalId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDansal(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDansal(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePhotoComment(arg0: PhotoCommentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhotoComment(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhotoComment(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReportNote(arg0: NoteId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReportNote(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReportNote(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReview(arg0: ReviewId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async dismissReport(arg0: ReportId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissReport(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissReport(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterDansals(arg0: DansalFilter): Promise<Array<Dansal>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDansals(to_candid_DansalFilter_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDansals(to_candid_DansalFilter_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovalNotifications(): Promise<Array<ApprovalNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovalNotifications();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovalNotifications();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageRating(arg0: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return result;
        }
    }
    async getComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getDansal(arg0: DansalId): Promise<Dansal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDansal(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDansal(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDansals(): Promise<Array<Dansal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDansals();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDansals();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryPhotos();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryPhotos();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDansalAnalytics(): Promise<Array<DansalAnalytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDansalAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDansalAnalytics();
            return result;
        }
    }
    async getMyDansals(): Promise<Array<Dansal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDansals();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDansals();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFavorites(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFavorites();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizerProfile(arg0: Principal): Promise<OrganizerPublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizerProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizerProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDansals(): Promise<Array<Dansal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDansals();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDansals();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPhotos();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPhotos();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotoComments(arg0: bigint): Promise<Array<PhotoComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoComments(arg0);
            return result;
        }
    }
    async getReportNotes(arg0: ReportId): Promise<Array<ReportNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportNotes(arg0);
            return result;
        }
    }
    async getReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async isDansalLiked(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDansalLiked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDansalLiked(arg0);
            return result;
        }
    }
    async isFavorited(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFavorited(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFavorited(arg0);
            return result;
        }
    }
    async likePhoto(arg0: PhotoId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePhoto(arg0);
            return result;
        }
    }
    async listDansals(): Promise<Array<Dansal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDansals();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDansals();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPhotos();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPhotos();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReports();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReports();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationSeen(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationSeen(arg0);
            return result;
        }
    }
    async registerUser(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_UserProfile_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_UserProfile_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectDansal(arg0: DansalId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDansal(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDansal(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectPhoto(arg0: PhotoId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPhoto(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPhoto(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: Principal, arg1: Role): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n48(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n48(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReport(arg0: SubmitReportRequest): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReport(to_candid_SubmitReportRequest_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Report_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReport(to_candid_SubmitReportRequest_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Report_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleDansalLike(arg0: bigint): Promise<LikeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDansalLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDansalLike(arg0);
            return result;
        }
    }
    async toggleFavorite(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0);
            return result;
        }
    }
    async togglePhotoLike(arg0: bigint): Promise<LikeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePhotoLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePhotoLike(arg0);
            return result;
        }
    }
    async updateDansal(arg0: DansalId, arg1: UpdateDansalRequest): Promise<{
        __kind__: "ok";
        ok: Dansal;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDansal(arg0, to_candid_UpdateDansalRequest_n55(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDansal(arg0, to_candid_UpdateDansalRequest_n55(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrganizerBio(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrganizerBio(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrganizerBio(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadPhoto(arg0: AddPhotoRequest): Promise<GalleryPhoto> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(await to_candid_AddPhotoRequest_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GalleryPhoto_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(await to_candid_AddPhotoRequest_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GalleryPhoto_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAdminPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPin(arg0);
            return result;
        }
    }
}
function from_candid_ApprovalNotification_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalNotification): ApprovalNotification {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Dansal_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dansal): Dansal {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryPhoto_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryPhoto): Promise<GalleryPhoto> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ReportTargetType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportTargetType): ReportTargetType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Dansal]): Dansal | null {
    return value.length === 0 ? null : from_candid_Dansal_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrganizerPublicProfile]): OrganizerPublicProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DansalId;
    status: _ApprovalStatus;
    latitude: number;
    contactName: string;
    province: string;
    appreciationCount: bigint;
    date: string;
    createdAt: bigint;
    time: string;
    organizerName: string;
    likedBy: Array<Principal>;
    district: string;
    foodTypes: Array<string>;
    viewCount: bigint;
    longitude: number;
    organizerPrincipal: Principal;
    category: string;
    locationLink: string;
    contactPhone: string;
}): {
    id: DansalId;
    status: ApprovalStatus;
    latitude: number;
    contactName: string;
    province: string;
    appreciationCount: bigint;
    date: string;
    createdAt: bigint;
    time: string;
    organizerName: string;
    likedBy: Array<Principal>;
    district: string;
    foodTypes: Array<string>;
    viewCount: bigint;
    longitude: number;
    organizerPrincipal: Principal;
    category: string;
    locationLink: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: from_candid_ApprovalStatus_n11(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        contactName: value.contactName,
        province: value.province,
        appreciationCount: value.appreciationCount,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        organizerName: value.organizerName,
        likedBy: value.likedBy,
        district: value.district,
        foodTypes: value.foodTypes,
        viewCount: value.viewCount,
        longitude: value.longitude,
        organizerPrincipal: value.organizerPrincipal,
        category: value.category,
        locationLink: value.locationLink,
        contactPhone: value.contactPhone
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PhotoId;
    status: _ApprovalStatus;
    uploaderName: string;
    appreciationCount: bigint;
    likedBy: Array<Principal>;
    uploaderPrincipal: Principal;
    caption: string;
    image: _ExternalBlob;
    uploadedAt: bigint;
}): Promise<{
    id: PhotoId;
    status: ApprovalStatus;
    uploaderName: string;
    appreciationCount: bigint;
    likedBy: Array<Principal>;
    uploaderPrincipal: Principal;
    caption: string;
    image: ExternalBlob;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        status: from_candid_ApprovalStatus_n11(_uploadFile, _downloadFile, value.status),
        uploaderName: value.uploaderName,
        appreciationCount: value.appreciationCount,
        likedBy: value.likedBy,
        uploaderPrincipal: value.uploaderPrincipal,
        caption: value.caption,
        image: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.image),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    approvedAt: bigint;
    seen: boolean;
    targetName: string;
    targetType: _ReportTargetType;
    targetId: bigint;
}): {
    id: bigint;
    approvedAt: bigint;
    seen: boolean;
    targetName: string;
    targetType: ReportTargetType;
    targetId: bigint;
} {
    return {
        id: value.id,
        approvedAt: value.approvedAt,
        seen: value.seen,
        targetName: value.targetName,
        targetType: from_candid_ReportTargetType_n29(_uploadFile, _downloadFile, value.targetType),
        targetId: value.targetId
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    displayName: string;
    role: _Role;
    bioUpdatedAt: [] | [bigint];
    registeredAt: bigint;
}): {
    bio: string;
    principal: Principal;
    displayName: string;
    role: Role;
    bioUpdatedAt?: bigint;
    registeredAt: bigint;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        displayName: value.displayName,
        role: from_candid_Role_n36(_uploadFile, _downloadFile, value.role),
        bioUpdatedAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.bioUpdatedAt)),
        registeredAt: value.registeredAt
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReportId;
    status: _ReportStatus;
    description: [] | [string];
    reporterPrincipal: Principal;
    timestamp: bigint;
    targetType: _ReportTargetType;
    targetId: bigint;
    reason: {
        other: null;
    } | {
        fake: null;
    } | {
        inappropriate: null;
    } | {
        spam: null;
    };
}): {
    id: ReportId;
    status: ReportStatus;
    description?: string;
    reporterPrincipal: Principal;
    timestamp: bigint;
    targetType: ReportTargetType;
    targetId: bigint;
    reason: Variant_other_fake_inappropriate_spam;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n43(_uploadFile, _downloadFile, value.status),
        description: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.description)),
        reporterPrincipal: value.reporterPrincipal,
        timestamp: value.timestamp,
        targetType: from_candid_ReportTargetType_n29(_uploadFile, _downloadFile, value.targetType),
        targetId: value.targetId,
        reason: from_candid_variant_n46(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PhotoComment;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PhotoComment;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _NoteId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: NoteId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Review;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Review;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dansal: null;
} | {
    photo: null;
}): ReportTargetType {
    return "dansal" in value ? ReportTargetType.dansal : "photo" in value ? ReportTargetType.photo : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizer: null;
} | {
    admin: null;
} | {
    user: null;
} | {
    superAdmin: null;
}): Role {
    return "organizer" in value ? Role.organizer : "admin" in value ? Role.admin : "user" in value ? Role.user : "superAdmin" in value ? Role.superAdmin : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    dismissed: null;
} | {
    actioned: null;
}): ReportStatus {
    return "pending" in value ? ReportStatus.pending : "dismissed" in value ? ReportStatus.dismissed : "actioned" in value ? ReportStatus.actioned : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    fake: null;
} | {
    inappropriate: null;
} | {
    spam: null;
}): Variant_other_fake_inappropriate_spam {
    return "other" in value ? Variant_other_fake_inappropriate_spam.other : "fake" in value ? Variant_other_fake_inappropriate_spam.fake : "inappropriate" in value ? Variant_other_fake_inappropriate_spam.inappropriate : "spam" in value ? Variant_other_fake_inappropriate_spam.spam : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Dansal;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Dansal;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Dansal_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Dansal>): Array<Dansal> {
    return value.map((x)=>from_candid_Dansal_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalNotification>): Array<ApprovalNotification> {
    return value.map((x)=>from_candid_ApprovalNotification_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryPhoto>): Promise<Array<GalleryPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryPhoto_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n34(_uploadFile, _downloadFile, x));
}
async function to_candid_AddPhotoRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddPhotoRequest): Promise<_AddPhotoRequest> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_DansalFilter_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DansalFilter): _DansalFilter {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ReportTargetType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportTargetType): _ReportTargetType {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitReportRequest_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitReportRequest): _SubmitReportRequest {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateDansalRequest_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateDansalRequest): _UpdateDansalRequest {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uploaderName: string;
    caption: string;
    image: ExternalBlob;
}): Promise<{
    uploaderName: string;
    caption: string;
    image: _ExternalBlob;
}> {
    return {
        uploaderName: value.uploaderName,
        caption: value.caption,
        image: await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.image)
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    province?: string;
    timeStart?: string;
    district?: string;
    category?: string;
    timeEnd?: string;
    foodType?: string;
}): {
    province: [] | [string];
    timeStart: [] | [string];
    district: [] | [string];
    category: [] | [string];
    timeEnd: [] | [string];
    foodType: [] | [string];
} {
    return {
        province: value.province ? candid_some(value.province) : candid_none(),
        timeStart: value.timeStart ? candid_some(value.timeStart) : candid_none(),
        district: value.district ? candid_some(value.district) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        timeEnd: value.timeEnd ? candid_some(value.timeEnd) : candid_none(),
        foodType: value.foodType ? candid_some(value.foodType) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description?: string;
    targetType: ReportTargetType;
    targetId: bigint;
    reason: Variant_other_fake_inappropriate_spam;
}): {
    description: [] | [string];
    targetType: _ReportTargetType;
    targetId: bigint;
    reason: {
        other: null;
    } | {
        fake: null;
    } | {
        inappropriate: null;
    } | {
        spam: null;
    };
} {
    return {
        description: value.description ? candid_some(value.description) : candid_none(),
        targetType: to_candid_ReportTargetType_n52(_uploadFile, _downloadFile, value.targetType),
        targetId: value.targetId,
        reason: to_candid_variant_n54(_uploadFile, _downloadFile, value.reason)
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    contactName?: string;
    province?: string;
    date?: string;
    time?: string;
    organizerName?: string;
    district?: string;
    foodTypes?: Array<string>;
    longitude?: number;
    category?: string;
    locationLink?: string;
    contactPhone?: string;
}): {
    latitude: [] | [number];
    contactName: [] | [string];
    province: [] | [string];
    date: [] | [string];
    time: [] | [string];
    organizerName: [] | [string];
    district: [] | [string];
    foodTypes: [] | [Array<string>];
    longitude: [] | [number];
    category: [] | [string];
    locationLink: [] | [string];
    contactPhone: [] | [string];
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        contactName: value.contactName ? candid_some(value.contactName) : candid_none(),
        province: value.province ? candid_some(value.province) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        time: value.time ? candid_some(value.time) : candid_none(),
        organizerName: value.organizerName ? candid_some(value.organizerName) : candid_none(),
        district: value.district ? candid_some(value.district) : candid_none(),
        foodTypes: value.foodTypes ? candid_some(value.foodTypes) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        locationLink: value.locationLink ? candid_some(value.locationLink) : candid_none(),
        contactPhone: value.contactPhone ? candid_some(value.contactPhone) : candid_none()
    };
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    organizer: null;
} | {
    admin: null;
} | {
    user: null;
} | {
    superAdmin: null;
} {
    return value == Role.organizer ? {
        organizer: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value == Role.superAdmin ? {
        superAdmin: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportTargetType): {
    dansal: null;
} | {
    photo: null;
} {
    return value == ReportTargetType.dansal ? {
        dansal: null
    } : value == ReportTargetType.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_other_fake_inappropriate_spam): {
    other: null;
} | {
    fake: null;
} | {
    inappropriate: null;
} | {
    spam: null;
} {
    return value == Variant_other_fake_inappropriate_spam.other ? {
        other: null
    } : value == Variant_other_fake_inappropriate_spam.fake ? {
        fake: null
    } : value == Variant_other_fake_inappropriate_spam.inappropriate ? {
        inappropriate: null
    } : value == Variant_other_fake_inappropriate_spam.spam ? {
        spam: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
